name: Build & Release SDK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      VSWHERE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build SDK (x86 & x64)
        shell: powershell
        run: |
          .\build_sdk.bat

      - name: Package release assets
        shell: powershell
        run: |
          Compress-Archive -Path output\x86\* -DestinationPath usb101d_sdk_x86.zip -Force
          Compress-Archive -Path output\x64\* -DestinationPath usb101d_sdk_x64.zip -Force

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          files: |
            usb101d_sdk_x86.zip
            usb101d_sdk_x64.zip

permissions:
  contents: write 